[package]
name = "spotted_artnet"
version = "0.1.0"
authors = ["Ollie Nye <ollie@nyemail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
